In [3]:
import numpy as np
import random

In [12]:
np.array([[0, 1], [0, 5]])

array([[0, 1],
       [0, 5]])

In [15]:
b = np.sum([[0, 1], [2, 5]], axis=0)
print b
b.shape

[2 6]


(2,)

In [14]:
a = np.sum([[0, 1], [2, 5]], axis=0, keepdims = True)
print a

[[2 6]]


In [10]:
a.shape

(1, 2)

In [16]:
a.T

array([[2],
       [6]])

In [25]:
random.seed(123)
x = range(10)
random.shuffle(x, random.random)
print x
random.shuffle(x, random.random)
print x

[7, 1, 4, 2, 6, 5, 8, 3, 9, 0]
[6, 9, 8, 5, 3, 7, 0, 4, 2, 1]


In [26]:
x
x[0:5]

[6, 9, 8, 5, 3]